### ISSUE TITLE
大佬，你这个好像离线的app  不行啊。

### ISSUE THREAD

**Issue by xiachaoxulu** [CaiJinFu/TBSDemo#7]
大佬，你这个好像离线的app  不行啊。 还得在线下载core。
报错这个：
at com.tencent.smtt.sdk.QbSdk.preinstallStaticTbs(Unknown Source:7)

**Comment by CaiJinFu** [comment]
> 大佬，你这个好像离线的app 不行啊。 还得在线下载core。 报错这个： at com.tencent.smtt.sdk.QbSdk.preinstallStaticTbs(Unknown Source:7)

静态集成方案有问题，可参考[TBS文件浏览自主安装内核方案](https://blog.csdn.net/qq_34205629/article/details/122375262)
